include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    body_might_complete_normally_nullable: ignore
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"

formatter:
  trailing_commas: preserve

linter:
  rules:
    avoid_print: true
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
